name: topochip-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - seaborn
  - pip
  - pip:
      - shap
      - cellpose
